name: Upload coverage reports to Codecov
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Julia 1.11.0
        uses: julia-actions/setup-julia@v1
        with:
          version: "1.11.0"

      - name: Add dependencies as in local environment
        run: |
          julia --project -e '
            using Pkg;
            Pkg.add([
              PackageSpec(url="https://github.com/aclai-lab/SoleBase.jl", rev="main"),
              PackageSpec(url="https://github.com/aclai-lab/MultiData.jl", rev="main"),
              PackageSpec(url="https://github.com/aclai-lab/SoleLogics.jl", rev="dev"),
              PackageSpec(url="https://github.com/aclai-lab/SoleData.jl", rev="dev"),
              PackageSpec(url="https://github.com/aclai-lab/SoleModels.jl", rev="main")
            ])'

      - uses: julia-actions/julia-buildpkg@v1

      - uses: julia-actions/julia-runtest@v1

      - uses: julia-actions/julia-processcoverage@v1

      - uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: aclai-lab/ModalAssociationRules.jl
