name: CI with Coverage

on: [push, pull_request]

jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    permissions:
      actions: write
      contents: read

    strategy:
      fail-fast: false
      matrix:
        version: ['1.11', 'lts']
        os: [ubuntu-latest]
        arch: [x64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Julia
        uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}

      - name: Add dependencies as in local environment
        run: |
          julia --project -e '
            using Pkg;
            Pkg.add([
              PackageSpec(url="https://github.com/aclai-lab/SoleBase.jl", rev="main"),
              PackageSpec(url="https://github.com/aclai-lab/MultiData.jl", rev="main"),
              PackageSpec(url="https://github.com/aclai-lab/SoleLogics.jl", rev="main"),
              PackageSpec(url="https://github.com/aclai-lab/SoleData.jl", rev="main"),
              PackageSpec(url="https://github.com/aclai-lab/SoleModels.jl", rev="main")
            ])'

      - name: Restore cache
        uses: julia-actions/cache@v2

      - name: Build package
        uses: julia-actions/julia-buildpkg@v1

      - name: Run tests
        uses: julia-actions/julia-runtest@v1

      - name: Process test coverage
        uses: julia-actions/julia-processcoverage@v1

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: aclai-lab/ModalAssociationRules.jl
          files: lcov.info
          fail_ci_if_error: false
